name: Build Docker Container

on:
  push:
    paths:
      - index.html
env:
  MANAGER_HOST_NAME: direct.labs.play-with-docker.com
  MANAGER_USERNAME: ip172-18-0-128-cpasjliim2rg00eb2nig
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    
      - name: Add SSH private key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRV_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519   

      - name: Test ssh connection
        run: |
           ssh -o StrictHostKeyChecking=no ${{ env.MANAGER_USERNAME }}@${{ env.MANAGER_HOST_NAME }} "whoami"
           
            
