name: Build Docker Container

on:
  push:
    paths:
      - index.html
env:
  MANAGER_HOST_NAME: direct.labs.play-with-docker.com
  MANAGER_USERNAME: ip172-18-0-66-cp9qekq91nsg00al79pg
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: imadtoumi/interview:latest

      - name: Create docker-compose on remote host
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.MANAGER_HOST_NAME }}
          username: ${{ env.MANAGER_USERNAME }}
          key: ${{ secrets.SSH_PRV_KEY }}
          script: |
            echo "
              version: '3.8'
              services:
                web:
                  image: imadtoumi/interview:latest
                  deploy:
                    placement:
                      constraints:
                        - node.role == worker
                  ports:
                    - 80:80
            " > docker-compose.yml
            
            docker stack deploy -c ~/docker-compose.yml interview_App
    
