name: Build Docker Container

on:
  push:
    paths:
      - index.html
env:
  MANAGER_HOST_NAME: direct.labs.play-with-docker.com
  MANAGER_USERNAME: ip172-18-0-128-cpasjliim2rg00eb2nig
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    
      - name: generate sshkey
        run : |
          ssh-keygen -t ed25519 -P "" -f ~/.ssh/id_ed25519 

      - name: Test ssh connection
        run: |
           ssh -vvv -o StrictHostKeyChecking=no ip172-18-0-99-cpb28niim2rg00cm0kkg@direct.labs.play-with-docker.com "whoami"
           
            
