name: Build Docker Container

on:
  push:
    paths:
      - index.html

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: imadtoumi/interview:latest

      - name: Add key to ssh file
        run: |
          echo "${{ secrets.SSH_PRV_KEY }}" >> ~/.ssh/id_ed25519

      - name: cat the ssh file
        run: cat ~/.ssh/id_ed25519

      - name: Generate ssh key and connect
        run: | 
          ssh -vvv -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 ip172-18-0-110-cp9n7i2im2rg008hg9o0@direct.labs.play-with-docker.com "whoami"

    
