name: Build Docker Container

on:
  push:
    paths:
      - index.html

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: imadtoumi/interview:latest
          
      - name: Generate SSH key
        run: |
          ssh-keygen -t ed25519 -P "" -f ~/.ssh/id_ed25519

      - name: List .ssh directory contents
        run: ls -al ~/.ssh


      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ip172-18-0-49-cp978liim2rg00fafkdg@direct.labs.play-with-docker.com
          key: ~/.ssh/id_ed25519
          script: whoami

      - name: try conenction 
        run : ssh -vvv -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 ip172-18-0-125-cp93qv8l2o9000fu7d10@direct.labs.play-with-docker.com 'ls'
          
      - name: Create docker-compose.yaml
        run: |
          ssh -vvv -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 ip172-18-0-125-cp93qv8l2o9000fu7d10@direct.labs.play-with-docker.com '
          echo "
          version: '3.8'
          services:
            web:
              image: simplecloudquestions/example_docker:latest
              deploy:
                placement:
                  constraints:
                    - node.labels.role == worker
              ports:
                - 80:80
          " > docker-compose.yml'
